export const SET_INITIAL_STORE = 'SET_INITIAL_STORE';

// user
export const SET_USER_TOKEN = 'SET_USER_TOKEN';
export const SET_USER_PROP = 'SET_USER_PROP';
export const SET_USER_PHOTO = 'SET_USER_PHOTO';
export const SET_USER_PHONE_NUMBER = 'SET_USER_PHONE_NUMBER';

// cards
export const ADD_CARD = 'ADD_CARD';
export const SET_CARD_PROP = 'SET_CARD_PROP';
export const SET_CARD_PRICE = 'SET_CARD_PRICE';
export const ADD_CARD_PHOTO = 'ADD_CARD_PHOTO';

// local state
export const SET_CURRENT_CARD = 'SET_CURRENT_CARD';
export const SET_DECK_CARDS = 'SET_DECK_CARDS';
export const SET_MATCH_INDICATOR = 'SET_MATCH_INDICATOR';

export const SET_SHELF_CARDS = 'SET_SHELF_CARDS';
export const ADD_CARD_TO_LIKED = 'ADD_CARD_TO_LIKED';
export const ADD_CARD_TO_DISLIKED = 'ADD_CARD_TO_DISLIKED';
export const ADD_CARD_TO_ARCHIVE = 'ADD_CARD_TO_ARCHIVE';

// chatbot
export const CHATBOT_SET_IS_WRITING = 'CHATBOT_SET_IS_WRITING';
export const SEND_CHATBOT_MESSAGE = 'SEND_CHATBOT_MESSAGE';
export const SET_CURRENT_SCENARIO_ID = 'SET_CURRENT_SCENARIO_ID';
