export const SET_INITIAL_STORE = 'SET_INITIAL_STORE';

// user
export const SET_USER_TOKEN = 'SET_USER_TOKEN';
export const SET_USER_NAME = 'SET_USER_NAME';
export const SET_USER_PHOTO = 'SET_USER_PHOTO';
export const SET_USER_PHONE_NUMBER = 'SET_USER_PHONE_NUMBER';

// cards
export const ADD_CARD = 'ADD_CARD';
export const SET_CARD_PROP = 'SET_CARD_PROP';
export const SET_CARD_PRICE = 'SET_CARD_PRICE';
export const SET_CARD_NUMBER_OF_PEOPLE = 'SET_CARD_NUMBER_OF_PEOPLE';
export const SET_CARD_DESCRIPTION = 'SET_CARD_DESCRIPTION';

// local state
export const SET_CURRENT_CARD = 'SET_CURRENT_CARD';
export const SET_DECK_CARDS = 'SET_DECK_CARDS';

export const SET_SHELF_CARDS = 'SET_SHELF_CARDS';
export const ADD_CARD_TO_LIKED = 'ADD_CARD_TO_LIKED';
export const ADD_CARD_TO_DISLIKED = 'ADD_CARD_TO_DISLIKED';
